apiVersion: v1
kind: Service
metadata:
  name: exchange-service
spec:
  type: NodePort
  selector:
    app: exchange-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
